<?php

/**
 * @file
 * Contains santander_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function santander_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the santander_search module.
    case 'help.page.santander_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Santander search') . '</p>';
      return $output;

    default:
  }
}
